name: Build and deploy Statiq site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore and build
      working-directory: ./StatiqSite
      run: |
        dotnet restore
        dotnet run --project .

    - name: Copy CNAME to output
      if: ${{ always() }}
      run: |
        if [ -f CNAME ]; then mkdir -p StatiqSite/output && cp CNAME StatiqSite/output/CNAME || true; fi

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./StatiqSite/output
        publish_branch: gh-pages
